In [2]:
##libraries required
import math
import re
from nltk.metrics import ConfusionMatrix
import random
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import pickle
import numpy
import csv
from sklearn.feature_extraction import DictVectorizer
from sklearn.preprocessing import MaxAbsScaler
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from matplotlib import interactive
interactive(True)
import pandas as pd
import seaborn

# DATA INSIGHTS

In [4]:
pdf = pd.read_csv('Training-data.csv')

In [53]:
pdf.head(10)

query     food_type  \
0  let we are meet tommorrow 7am in mc donalds fo...    mc donalds   
1   if you available lets meet for tomorrow noontime           NaN   
2  let's get this hammered out tomorrow at lunch....  cafe on main   
3  i'll give you a call tomorrow at 12:45, how do...           NaN   
4  please meet me in multipurpose room 2 at after...           NaN   
5  we should meet at paul's on 23rd tomorrow 6:00...        paul's   
6  i want to have one-to-one review with you. let...           NaN   
7                are you available tuesday at 17:30?           NaN   
8  i want to meet with you in your office at 7:45...           NaN   
9  let's meet at the school library at 12 at noon...           NaN   

                  time       date             location  
0                  7am  tommorrow                  NaN  
1             noontime   tomorrow                  NaN  
2    9:45 in the night   tomorrow                  NaN  
3                12:45   tomorrow                  NaN  
4       afternoon 1:15        NaN  multipurpose room 2  
5              6:00 PM   tomorrow                  NaN  
6            after 5pm      today                  NaN  
7                17:30    tuesday                  NaN  
8  7:45 in the morning        NaN          your office  
9           12 at noon        NaN       school library

In [7]:
pdf['query'].values

array(['let we are meet tommorrow 7am in mc donalds for our contract.',
       'if you available lets meet for tomorrow noontime',
       "let's get this hammered out tomorrow at lunch. say 9:45 in the night at the cafe on main?",
       ...,
       'We will meet for business discussion at Andhra Bar on 2nd 2 PM in Pittsburg',
       'We will meet for business discussion at Albanian Bar on 2nd 2 PM in Pittsburg',
       'We will meet for business discussion at Ainu Bar on 2nd 2 PM in Pittsburg'],
      dtype=object)

In [8]:
maxlen = 0
for val in pdf['query'].values:
    l = len(val.split(' '))
    if(l > maxlen):
        maxlen = l 
        

In [9]:
maxlen # Maximum Length of the sentence in whole data

46

# FEATURE CREATION

In [475]:
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding, Flatten, Input
from keras.layers import LSTM
from keras.datasets import imdb
from keras.preprocessing import text

In [263]:
from __future__ import print_function


from keras.models import load_model
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding, Dropout
from keras.datasets import imdb
from keras.optimizers import SGD, RMSprop
import keras
import numpy as np
import math
from keras.layers import Dense, Embedding, Dropout, LSTM, RepeatVector , TimeDistributed, Activation

In [264]:

from keras.preprocessing.text import Tokenizer

In [265]:
docs = pdf['query'].values

In [266]:
t = Tokenizer()
t.fit_on_texts(docs)

In [267]:
vocab_size = len(t.word_index) + 1

In [268]:
vocab_size # SIZE OF MAXIMUM VOCAB LENGTH 

3069

In [270]:
encoded_docs = t.texts_to_sequences(docs)

In [271]:
encoded_docs

[[123, 8, 74, 3, 1828, 1613, 2, 442, 443, 6, 41, 48],
 [60, 11, 127, 24, 3, 6, 15, 2116],
 [47,
  46,
  26,
  1181,
  84,
  15,
  1,
  17,
  414,
  134,
  163,
  2,
  5,
  112,
  1,
  5,
  288,
  7,
  543],
 [252, 196, 11, 12, 45, 15, 1, 107, 163, 42, 561, 91, 1289],
 [34, 3, 16, 2, 2117, 213, 59, 1, 57, 56, 118, 4, 61, 5, 48],
 [8, 147, 3, 1, 1366, 7, 679, 15, 99, 70, 33],
 [9, 55, 4, 19, 189, 4, 189, 580, 52, 11, 24, 19, 12, 13, 40, 90, 506],
 [74, 11, 127, 106, 1, 631, 53],
 [9, 55, 4, 3, 52, 11, 2, 58, 89, 1, 82, 163, 2, 5, 44],
 [47, 3, 1, 5, 1002, 459, 1, 107, 1, 140, 6, 5, 1944, 1945, 75, 41, 1946],
 [14, 8, 19, 12, 45, 15, 1, 82, 53, 2, 5, 44],
 [8, 25, 3, 15, 112, 105, 118],
 [886,
  1204,
  478,
  129,
  21,
  11,
  231,
  7,
  591,
  341,
  664,
  1,
  44,
  99,
  53,
  2,
  191,
  10,
  1367],
 [47, 176, 181, 2, 5, 57, 95, 53],
 [24, 110, 3, 40, 2, 119, 1431, 1368, 1, 132, 44, 95],
 [49, 153, 118, 2, 5, 57, 2, 5, 288, 259],
 [9, 32, 493, 4, 176, 4, 28, 13, 52, 41, 1205, 15,

In [272]:
from keras.preprocessing.sequence import pad_sequences
padded_docs = pad_sequences(encoded_docs, maxlen=max_features, padding='post')

In [273]:
docs

array(['let we are meet tommorrow 7am in mc donalds for our contract.',
       'if you available lets meet for tomorrow noontime',
       "let's get this hammered out tomorrow at lunch. say 9:45 in the night at the cafe on main?",
       ...,
       'We will meet for business discussion at Andhra Bar on 2nd 2 PM in Pittsburg',
       'We will meet for business discussion at Albanian Bar on 2nd 2 PM in Pittsburg',
       'We will meet for business discussion at Ainu Bar on 2nd 2 PM in Pittsburg'],
      dtype=object)

In [604]:
y=[]
i=0
for value in pdf['query'].values:
    vector=[]
    words= value.split(' ')
    food_type_words = str(pdf['food_type'][i]).split(' ')
    time_words = str(pdf['time'][i]).split(' ') 
    date_words = str(pdf['date'][i]).split(' ') 
    location_words = str(pdf['location'][i]).split(' ') 
    for word in words:
        if word in food_type_words:
            vector.append(1)
        elif word in time_words:
            vector.append(2)
        elif word in date_words:
            vector.append(3)  
        elif word in location_words:
            vector.append(4)  
        else:
            vector.append(0)
    #print(vector)
    y.append(vector)
    i = i +1        
        
    

In [605]:
from keras.preprocessing.sequence import pad_sequences
padded_labels = pad_sequences(y, maxlen=max_features, padding='post')

In [606]:
padded_docs.shape

(52798, 46)

In [607]:
padded_labels.shape

(52798, 46)

# DATA PREPARATION 

In [608]:
x_train , x_test, y_train , y_test = train_test_split(padded_docs, padded_labels, test_size=0.1,random_state=420)

In [609]:
x_train.shape

(47518, 46)

In [610]:
y_train.shape

(47518, 46)

In [611]:
x_test.shape

(5280, 46)

In [612]:
y_test.shape

(5280, 46)

# MODEL TRAINING 

In [613]:
y_train_vectorized = keras.utils.to_categorical(y_train, 5)

In [614]:

model = Sequential()

model.add(Embedding(3069, 1000, input_length=46))
# Recurrent layer
model.add(LSTM(46, input_shape=(46, 1000), return_sequences=True))

# Fully connected layer
model.add(Dense(5, activation='softmax'))


model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.summary()

Model: "sequential_81"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_56 (Embedding)     (None, 46, 1000)          3069000   
_________________________________________________________________
lstm_63 (LSTM)               (None, 46, 46)            192648    
_________________________________________________________________
dense_63 (Dense)             (None, 46, 5)             235       
Total params: 3,261,883
Trainable params: 3,261,883
Non-trainable params: 0
_________________________________________________________________


In [615]:
history = model.fit(x_train, y_train_vectorized,batch_size = 100, epochs=10,verbose=1)
   

Epoch 1/10
47518/47518 [==============================] - 77s 2ms/step - loss: 0.1008 - acc: 0.9722
Epoch 2/10
47518/47518 [==============================] - 76s 2ms/step - loss: 0.0413 - acc: 0.9854
Epoch 3/10
47518/47518 [==============================] - 73s 2ms/step - loss: 0.0320 - acc: 0.9886
Epoch 4/10
47518/47518 [==============================] - 74s 2ms/step - loss: 0.0272 - acc: 0.9903
Epoch 5/10
47518/47518 [==============================] - 74s 2ms/step - loss: 0.0242 - acc: 0.9914
Epoch 6/10
47518/47518 [==============================] - 74s 2ms/step - loss: 0.0220 - acc: 0.9922
Epoch 7/10
47518/47518 [==============================] - 76s 2ms/step - loss: 0.0203 - acc: 0.9928
Epoch 8/10
47518/47518 [==============================] - 78s 2ms/step - loss: 0.0189 - acc: 0.9933
Epoch 9/10
47518/47518 [==============================] - 74s 2ms/step - loss: 0.0178 - acc: 0.9937
Epoch 10/10
47518/47518 [==============================] - 75s 2ms/step - loss: 0.0169 - acc: 0.9940

# MODEL PERFORMANCE 

In [616]:
x_test

array([[363,   3,   1, ...,   0,   0,   0],
       [ 46,  16, 332, ...,   0,   0,   0],
       [273, 510,  65, ...,   0,   0,   0],
       ...,
       [ 14,   8,  19, ...,   0,   0,   0],
       [  9,  19, 254, ...,   0,   0,   0],
       [ 29,  16, 368, ...,   0,   0,   0]], dtype=int32)

In [617]:
y_prediction = model.predict_classes(x_test, verbose=1)

5280/5280 [==============================] - 4s 785us/step


In [618]:
y_prediction.shape

(5280, 46)

In [619]:
y_test.shape

(5280, 46)

In [620]:
y_test[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=int32)

In [621]:
from sklearn.metrics import *
accuracy_score(y_test.flatten(), y_prediction.flatten())

0.9923666007905139

In [622]:

target_names = ['None', 'food_type', 'time' , 'date' , 'location']
print(classification_report(y_test.flatten(), y_prediction.flatten(), target_names=target_names))

              precision    recall  f1-score   support

        None       1.00      1.00      1.00    232912
   food_type       0.90      0.81      0.85       345
        time       0.89      0.85      0.87      3299
        date       0.91      0.93      0.92      4598
    location       0.90      0.92      0.91      1726

    accuracy                           0.99    242880
   macro avg       0.92      0.90      0.91    242880
weighted avg       0.99      0.99      0.99    242880



# RUN TIME TEST

In [543]:
val = "let's? get this hammered out tomorrow at lunch. say 9:45 in the night at the cafe on main?"
length = val.split(' ')

In [544]:
docs = []
docs.append(val)

In [545]:
encoded_test_docs = t.texts_to_sequences(docs)
padded_test_docs = pad_sequences(encoded_test_docs, maxlen=max_features, padding='post')


In [546]:
output_array_test = model2.predict(padded_test_docs)

In [547]:
prediction = model.predict_classes(padded_test_docs, verbose=1)

1/1 [==============================] - 2s 2s/step


In [548]:
prediction

array([[0, 0, 0, 0, 0, 3, 0, 0, 0, 2, 2, 2, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0]])

In [550]:
labelmap={ 0 : 'None' ,
         1: 'food_type',
         2: 'time',
         3: 'date',
         4: 'location'}


In [561]:
words = val.split(' ')
for i in range(0,len(words)):
    print(words[i] +  ' : ' + labelmap.get(prediction[0][i]))

let's? : None
get : None
this : None
hammered : None
out : None
tomorrow : date
at : None
lunch. : None
say : None
9:45 : time
in : time
the : time
night : time
at : None
the : time
cafe : food_type
on : None
main? : None
